apiVersion: v1
kind: Service
metadata:
  name: sftp-nodeport
spec:
  type: NodePort
  ports:
    - name: sftp
      port: 2022
      targetPort: sftp
      nodePort: 32022
      protocol: TCP
  selector:
    app.kubernetes.io/name: sftp
